name: scr2ocr

channels:
  - conda-forge

dependencies:
  - python =3.10
  - gxx =8.5  # required by JamSpell
  - swig =3 # required by JamSpell
  - pip
  - pillow
  - pyperclip
  - pytesseract
  - pip:
    - git+https://github.com/bakwc/JamSpell.git@0.0.12
  - conda-lock
  - pyinstaller
