name: scr2ocr

channels:
  - conda-forge

dependencies:
  - python =3.10
  - gxx =8.5  # [not win]
  - swig =4   # [not win]
  - pip
  - pillow
  - pyperclip
  - pytesseract
  - tesseract
  - conda-lock
  - pyinstaller

platforms:
  - linux-64
  - osx-64
  - win-64
